name: Video productions
favicon: null
layout_spectrum: 0.56221
typography_spectrum: 0.64292
title: 'Corporate video production services in Banff, Canmore and Lake Louise'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0f0e13'
    - '#bcc1c4'
    - '#4a699d'
    - '#fa3458'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
