name: Video productions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.893617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060606'
    - '#385483'
    - '#bbc0c6'
    - '#707c87'
  brandStrength: 0.8125
  lightness: 0.3297872
  saturation: 0.7808511
  rhythmicContrast: 0.4089547
purpose: []
