layout_spectrum: 1
color:
  saturation: 0.7808511
  brandStrength: 1
  lightness: 0.3297872
  brandColors:
    - '#FFFFFF'
    - '#38302F'
    - '#E0BE8F'
    - '#CFCDC7'
  rhythmicContrast: 0.4089547
typography_spectrum: 0.893617
name: Video productions
